name: Send release notification

on:
  workflow_call:
    inputs:
      succeeded:
        type: boolean
        required: true
      repository:
        type: string
        required: true
      version:
        type: string
        required: false
        default: ''
      run-id:
        type: string
        required: true
    secrets:
      bot_webhook_url:
        required: true
  
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.bot_webhook_url }}
          data: |
            { 
              "succeeded": ${{ inputs.succeeded }},
              "repository": "${{ inputs.repository }}",
              "version": "${{ inputs.version }}",
              "runId": "${{ inputs.run-id }}"
            }
